"""init schema

Revision ID: daf0779dfb50
Revises: 
Create Date: 2026-04-23 09:44:37.989006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'daf0779dfb50'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('icon', sa.String(length=32), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_parent_id'), 'categories', ['parent_id'], unique=False)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_table('tools',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.Column('tagline', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('developer', sa.String(length=128), nullable=True),
    sa.Column('launched_at', sa.Date(), nullable=True),
    sa.Column('is_iterating', sa.Boolean(), nullable=False),
    sa.Column('user_count', sa.String(length=64), nullable=True),
    sa.Column('form_factor', sa.String(length=32), nullable=False),
    sa.Column('is_free', sa.Boolean(), nullable=False),
    sa.Column('pricing_info', sa.String(length=255), nullable=True),
    sa.Column('gen_time_ms', sa.Integer(), nullable=True),
    sa.Column('need_vpn', sa.Boolean(), nullable=False),
    sa.Column('support_cli', sa.Boolean(), nullable=False),
    sa.Column('support_api', sa.Boolean(), nullable=False),
    sa.Column('official_url', sa.String(length=512), nullable=True),
    sa.Column('overall_score', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('usability_score', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('effect_score', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('price_score', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('speed_score', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tools_form_factor'), 'tools', ['form_factor'], unique=False)
    op.create_index(op.f('ix_tools_is_free'), 'tools', ['is_free'], unique=False)
    op.create_index(op.f('ix_tools_name'), 'tools', ['name'], unique=False)
    op.create_index(op.f('ix_tools_slug'), 'tools', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('avatar', sa.String(length=512), nullable=True),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('reviews',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('tool_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('score', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('dims', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reward_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_status'), 'reviews', ['status'], unique=False)
    op.create_index(op.f('ix_reviews_tool_id'), 'reviews', ['tool_id'], unique=False)
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.create_table('tool_audiences',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tool_id', sa.BigInteger(), nullable=False),
    sa.Column('audience', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tool_id', 'audience', name='uq_tool_audience')
    )
    op.create_index(op.f('ix_tool_audiences_audience'), 'tool_audiences', ['audience'], unique=False)
    op.create_index(op.f('ix_tool_audiences_tool_id'), 'tool_audiences', ['tool_id'], unique=False)
    op.create_table('tool_categories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tool_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tool_id', 'category_id', name='uq_tool_category')
    )
    op.create_index(op.f('ix_tool_categories_category_id'), 'tool_categories', ['category_id'], unique=False)
    op.create_index(op.f('ix_tool_categories_tool_id'), 'tool_categories', ['tool_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_categories_tool_id'), table_name='tool_categories')
    op.drop_index(op.f('ix_tool_categories_category_id'), table_name='tool_categories')
    op.drop_table('tool_categories')
    op.drop_index(op.f('ix_tool_audiences_tool_id'), table_name='tool_audiences')
    op.drop_index(op.f('ix_tool_audiences_audience'), table_name='tool_audiences')
    op.drop_table('tool_audiences')
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_tool_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_status'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tools_slug'), table_name='tools')
    op.drop_index(op.f('ix_tools_name'), table_name='tools')
    op.drop_index(op.f('ix_tools_is_free'), table_name='tools')
    op.drop_index(op.f('ix_tools_form_factor'), table_name='tools')
    op.drop_table('tools')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_parent_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
